#!/bin/bash

# Create simple 16x16 purple icon (base64 encoded minimal PNG)
echo "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAMElEQVQ4T2NkoBAwUqifYTQDhtEMGEYzYBgygJHhPwPD//8M/////8/AwPCfgYEBAKmzBxGB6R8jAAAAAElFTkSuQmCC" | base64 -d > icon16.png

# Create simple 48x48 purple icon
echo "iVBORw0KGgoAAAANSUhEUgAAADAAAAAwCAYAAABXAvmHAAAAQklEQVRoQ+2WMQ4AIAgD+f+f8UZXE1M7dYBOJUCBAgUKFChQoECBAgUKFChQoECBAgUKFChQoECBAgUKFCjwb8EFhSkQMcH7AIEAAAAASUVORK5CYII=" | base64 -d > icon48.png

# Create simple 128x128 purple icon  
echo "iVBORw0KGgoAAAANSUhEUgAAAIAAAACACAYAAADDPmHLAAAAxklEQVR42u3RAQ0AAAgDoL9/aM3hHFScAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQGBawMvYAMBOw+OvQAAAABJRU5ErkJggg==" | base64 -d > icon128.png

echo "Icons created!"
ls -lh icon*.png
